### ISSUE TITLE
Home page is not shown on vagrant up

### ISSUE THREAD

**Issue by Yarboa** [beyond-io/ultimatejob#13]
Running vagrant file
vagrant up
Vagrant is up
curl 127.0.0.1:8080
Page is not up.

I think Vagrant file should include the 
config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"

**Comment by RomTamam** [comment]
Fixed in PR #15 
@BarBenNaim Please close this issue
