### ISSUE TITLE
CronTab for WebScraping APIs

### ISSUE THREAD

**Issue by RomTamam** [beyond-io/ultimatejob#69]

**Comment by Yarboa** [comment]
Any Description here? Is it closed ? wip? which PR deals with it?

**Comment by RomTamam** [comment]
Not closed yet, PR #92 - wip 
Can you please grant me permissions for  beyond-io / ultimatejob ? to assign reviewers and add description?

**Comment by Yarboa** [comment]
@RomTamam, Is it closed? please update

**Comment by RomTamam** [comment]
Done

**Comment by RomTamam** [comment]
PR #107
